echo "This script creates a file showing the difference between"
echo "the output of creating the NWB files and validating them."
echo
echo "It should only be run after runing scripts:"
echo "../create_scripts/run_all.sh and validate_all.py"
echo
echo "Except for some warning messages, and any extra output"
echo "generated by create scripts, the result of the diff should"
echo "show that the output are mostly the same.  If it is not,"
echo "the diffrence may indicate there is a bug in the software."

diff -r ../text_output_files/create -x 0_README.txt ../text_output_files/validate > ../text_output_files/diff/cv_diff.txt

echo
echo "done creating diff."
echo "It is stored in file '../text_output_files/diff/cv_diff.txt'"
